chore: migrate to trunk-based development

diff --git a/.github/workflows/check_icon_pr.yml b/.github/workflows/check_icon_pr.yml
--- a/.github/workflows/check_icon_pr.yml
+++ b/.github/workflows/check_icon_pr.yml
@@ -1,32 +1,33 @@
 name: Check Icon PR
-on: pull_request
+on:
+  pull_request:
+    paths:
+      - 'icons/**'
+      - 'devicon.json'
 jobs:
   check:
     name: Check the `devicon.json` and the SVGs' quality
     runs-on: ubuntu-latest
-    if: startsWith(github.event.pull_request.title, 'new icon') || startsWith(github.event.pull_request.title, 'update icon')  # only checks icon PR
     steps:
       - uses: actions/checkout@v4
 
-      - name: Check if PR is develop
-        if: ${{ github.base_ref != 'develop' }}
+      - name: Check if PR targets master
+        if: ${{ github.base_ref != 'master' }}
         run: |
-          echo -e "The PR's base branch is \`${{ github.base_ref }}\`, but should be \`develop\`\nPlease change the PR so that it's based on, and merged into \`develop\`" > ./err_messages.txt
-          echo "wrong_branch=true" >> $GITHUB_ENV
+          echo "Error: This PR targets '${{ github.base_ref }}' but should target 'master'"
+          echo "Please change the PR so that it's based on, and merged into 'master'"
+          exit 1
 
       - uses: actions/setup-python@v5
-        if: ${{ !env.wrong_branch }}
         with:
           python-version: 3.8
 
       - name: Install dependencies
-        if: ${{ !env.wrong_branch }}
         run: |
           python -m pip install --upgrade pip
           pip install -r ./.github/scripts/requirements.txt
 
       - name: Run the check_svg script
-        if: ${{ !env.wrong_branch }}
         env:
           PR_TITLE: ${{ github.event.pull_request.title }}
         run: python ./.github/scripts/check_icon_pr.py "$PR_TITLE" ./icons ./devicon.json
